### ISSUE TITLE
multiple ports are never up to date

### ISSUE THREAD

**Issue by fgarcia** [opscode-cookbooks/firewall#26]
The current syntax for multiple ports:

    firewall_rule 'http/https' do
      protocol :tcp
      ports    [80, 443]
      action   :allow
    end

Does not seem to detect properly it is up to date. The rule is triggered on every single run. Splitting the ports into single port rules work OK

**Comment by wojnosystems** [comment]
Also getting this same issue. I have a base firewall role that opens out-bound 80 and 443 for debian updates. Then, the specific web server role is trying to open them for in-bound and it fails. There does not appear to be a direction test in the provider file for rules.

When you run the chef-client code, the rule name will be listed with the phrase "(up to date)" sitting to the right of it, seemingly skipped.

I have confirmed @tgarcia's recommendation of splitting up the rule, which works for grouped ports, but shouldn't work for individual ports. I think this can be solved if another check for directionality is added.

**Comment by martinb3** [comment]
Hi folks -- I think I resolved this in the latest master branch. Would you consider testing and reporting back? Thank you!
