### ISSUE TITLE
source getting list of ip addresses

### ISSUE THREAD

**Issue by seperman** [opscode-cookbooks/firewall#27]
Hello,

Is it possible for the 'source' to be list of ip addresses instead of a single ip? UFW seems to allow only one IP but it would be great to have a list of ips here in the cookbook.
Thanks

**Comment by gregkare** [comment]
You probably found a way around it by now, but you can loop over an array of IP addresses and use a resource for each IP:

```ruby
['10.0.0.1', '10.0.0.2'].each do |ip|
  firewall_rule 'myapplication' do
    port      13579
    source    ip
    direction :in
    interface 'eth0'
    action    :allow
  end
```

**Comment by seperman** [comment]
Cool. Thanks!
