### ISSUE TITLE
Add purge and ignore attribute parameter to resource 'firewall'

### ISSUE THREAD

**Issue by facastagnini** [opscode-cookbooks/firewall#36]
The resource 'firewall' is missing a key feature, handle the unmanaged firewall rules.
Chef should ensure that the only firewall rules present are the ones explicitly declared in the recipes.

Example:

1. Add fw rule to enable port 123
```
firewall 'ufw' do
  action :enable
end

firewall_rule 'http/https' do
  port        443
  action   :allow
end
```
2. Change port number to 1234
```
firewall 'ufw' do
  action :enable
end

firewall_rule 'http/https' do
  port        5443
  action   :allow
end
```

**Expected behavior:** The firewall rule to allow traffic on the port 123 should be removed and a new rule will allow traffic on the port 1234.
**Actual behavior:** A new rule is added allowing traffic on the port 1234, but the old rule allowing traffic on the port 123 is still active.

**Proposed solution:** 
1. Add attribute *purge*: If enabled it will remove the rules not declared with chef. Default disabled
2. Add attribute *ignore*: Array of regex to ignore unmanaged rules.
```
firewall 'ufw' do
  action :enable
  purge :enable
  ignore ['-j fail2ban-ssh' ]
end
```

Please apologies if there is already a way to accomplish this, I couldn't find it.

**Comment by martinb3** [comment]
Hello @facastagnini -- a `:flush` action has been added for iptables, which fixes this for iptables. I'm not sure `ufw` actually contains this functionality out of the box, and it seems like a bad idea to try to implement a lot of string parsing in chef if the underlying ufw software has no command for it.

**Comment by facastagnini** [comment]
Oh, I will give iptables a try then.
Thanks Martin

**Comment by facastagnini** [comment]
@martinb3 I look at the README and also you last changes, but I cant figure out how using the `iptables` provider with the `:flush` action will play nice with `fail2fan`.

Once I have a better understanding about how to use this cookbook properly I will try to improve the README so it is easier for the next folk and you don't have to repeat this answers.

Thanks!

**Comment by martinb3** [comment]
Indeed, emptying iptables with flush would remove rules from the fail2ban chain. I'm not sure this is something we should try to modify with chef either; it might not be delightful for people who already know what `flush` does to find out it doesn't flush completely on chef.

**Comment by facastagnini** [comment]
I understand your point about disappointing people changing the behavior of flush, but it is a blocker for everyone who wants to use opscode-cookbooks/fail2ban too.

I wonder what is the best way to address this.
Do you think it makes sense to add a `ignore` parameter like this:

```
firewall 'iptables' do
  action [:enable,:flush]
  ignore ['-j fail2ban-ssh' ]
end
```

If it defaults to an empty array `flush` will keep working as expected.

If this approach makes sense to you I can try to code it and provide a PR.

**Comment by martinb3** [comment]
I like that approach very much, and I'd merge a PR for that :)

**Comment by facastagnini** [comment]
Cool, let me see if I can figure that out!

**Comment by facastagnini** [comment]
Martin, I have not been able to write a decent patch to implement the
purge. I hope someone else can deal with it in the future.

**Comment by martinb3** [comment]
See also #77.
