### ISSUE TITLE
More testing of rules that don't specify a protocol

### ISSUE THREAD

**Issue by martinb3** [opscode-cookbooks/firewall#50]
Be sure we can do `:all` or omit the protocol.

**Comment by skiold** [comment]
We may be seeing this with v0.7.4 of the cookbook.

We specify only port 53 for our incoming dns and that produces a tcp only rule.

I'm moving to explicit rules for udp and tcp port 53 for the time being.

**Comment by shoekstra** [comment]
Hi,

At the moment the default is `:tcp` if no protocol is specified.  You cannot set 'all' so you will need to do explicit rules.

**Comment by martinb3** [comment]
#84 has added some major refactoring such that you can now specify `:none` and omit a protocol. I hope this helps! We'll be releasing soon, but we'd love any feedback before then :)
