### ISSUE TITLE
"No parent found for firewall_rule" error being thrown by Poise during compile

### ISSUE THREAD

**Issue by stottsan** [opscode-cookbooks/firewall#53]
I'm seeing this error while running in DigitalOcean, but only after a number of successful Chef runs.  I can't figure out how to recover, short of building a new droplet...  This doesn't happen in Vagrant/VirtualBox at all, and it doesn't happen on initial compile/converge or the first few runs.  

Any ideas?  I'm running Chef 12.2.1 on Ubuntu 14.04.2 LTS, and I'm using v1.0.1 of the firewall cookbook.  Thanks much!

```
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/my-tuning/recipes/default.rb
================================================================================

RuntimeError
------------
No parent found for firewall_rule[rule-name-here]

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/poise/libraries/subresources.rb:168:in `parent'
  /var/chef/cache/cookbooks/poise/libraries/subresources.rb:176:in `after_created'
  /var/chef/cache/cookbooks/my-tuning/recipes/firewall.rb:18:in `block in from_file'
  /var/chef/cache/cookbooks/my-tuning/recipes/firewall.rb:17:in `each'
  /var/chef/cache/cookbooks/my-tuning/recipes/firewall.rb:17:in `from_file'
  /var/chef/cache/cookbooks/my-tuning/recipes/default.rb:43:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/poise/libraries/subresources.rb:

161:          elsif !@parent
162:            # Find the last instance of the parent class as the default parent
163:            @run_context.resource_collection.each do |r|
164:              if r.is_a?(self.class.parent_type)
165:                @parent = ParentRef.new(r)
166:              end
167:            end
168>>           raise "No parent found for #{self}" unless @parent || self.class.parent_optional
169:          end
170:          @parent && @parent.resource
171:        end
172:  
173:        def after_created
174:          super
175:          begin
176:            parent.subresources.lookup(self) if parent
177:          rescue Chef::Exceptions::ResourceNotFound


Running handlers:
[2015-04-03T18:49:18-04:00] ERROR: Running exception handlers
Running handlers complete
[2015-04-03T18:49:18-04:00] ERROR: Exception handlers complete
[2015-04-03T18:49:18-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 11.561637599 seconds
[2015-04-03T18:49:18-04:00] ERROR: No parent found for firewall_rule[rule-name-here]
[2015-04-03T18:49:18-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

My firewall rule (basically) is as follows:
```
firewall_rule "rule-name-here" do
    source "1.1.1.1"
    position 1
    action :reject
  end
``` 

Thanks!

**Comment by martinb3** [comment]
Hi there -- I think this means you haven't declared a firewall resource first (or included the default recipe of this cookbook, which does that for you).

**Comment by stottsan** [comment]
Thanks @martinb3.  What's weird is that things work perfectly for a while -- until I start seeing this error.     

My cookbook's metadata includes ```depends``` statements for ufw and firewall, and here is the beginning of the run showing the cookbooks to be used:

```
root@ubuntu:~# chef-client
Starting Chef Client, version 12.2.1
resolving cookbooks for run list: ["users::sysadmins", "sudo", "apt::default", "ntp::default", "ufw::default", "my-tuning::default", "newrelic::server_monitor_agent"]
Synchronizing Cookbooks:
  - users
  - sudo
  - apt
  - my-tuning
  - ufw
  - firewall
  - ntp
  - poise
  - monit
  - newrelic
  - yum
  - python
  - curl
  - yum-epel
  - build-essential
  - nginx
  - bluepill
  - rsyslog
  - ohai
  - runit
  - chef-sugar
  - yum-mysql-community
  - mysql
  - xml
  - rbac
  - smf
  - php
  - chef_handler
  - windows
  - php-fpm
  - iis
  - percona
  - chef-vault
  - openssl
  - database
  - mysql2_chef_gem
  - postgresql
  - mariadb
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/my-tuning/recipes/default.rb
================================================================================
```

**Comment by martinb3** [comment]
Hi again -- you should not be depending on any cookbooks to use the firewall cookbook except `firewall` itself. `ufw`, `iptables`, and `firewall` are three different cookbooks that do things differently.

Can you show us where you `include_recipe 'firewall'` or where you declare a `firewall` resource in a recipe? I'm not sure why the Chef recipes would ever intermittently not compile; I'm guessing there's something else going on.

**Comment by stottsan** [comment]
Thanks again @martinb3.  

The ```ufw``` cookbook actually depends on this ```firewall``` cookbook which is how I got here in the first place.  :smile:  Here is the ```ufw``` cookbook's [metadata.rb file](https://github.com/opscode-cookbooks/ufw/blob/master/metadata.rb) and their [default recipe](https://github.com/opscode-cookbooks/ufw/blob/master/recipes/default.rb) leverages ```firewall_rule``` to allow for ssh connectivity.  

I'm not explicitly calling ```include_recipe 'firewall'``` or declaring a ```firewall``` resource, since everything worked OK in my testing with Berkshelf on VirtualBox/Vagrant.  And it works for a number of runs in production on DigitalOcean, so I didn't see the need.  I'll give that a shot and see if it helps.  

Thanks again!

**Comment by martinb3** [comment]
Ah @stottsan -- I didn't realize the `ufw` cookbook was depending on this! I recommend pinning back this cookbook to an earlier version, or moving off of the `ufw` cookbook to using this directly. Probably the ufw cookbook should have been pinning the firewall all along with pessimistic versioning. 

This cookbook originally only supported ufw, but now supports iptables and firewalld as well, and is meant as the next gen cookbook to replace ufw, iptables, etc. The ufw cookbook has not been substantively changed since December 2013, aside from a `s/opscode/chef/g` rename.
