### ISSUE TITLE
firewalld support on RHEL7 does not persistent, restart lost everything

### ISSUE THREAD

**Issue by yinym** [opscode-cookbooks/firewall#55]
With the latest firewall cookbook 1.0.2, it can support configuring firewalld rules. But I noticed that these rules are added by firewall-cmd without --permenant.

In this way, once we restarted the system, or simply restarted the firewalld service, everything will gone!

**Comment by martinb3** [comment]
Hello @yinym! The firewalld support was submitted by the community, so I can't say if that's a bug or not per se. But it looks like the contributor included a save action on the firewall resource. If you run that after adding it rules, it appears they would be persisted.

Hope this helps! If you'd like the default behavior changed, I'd welcome discussion and/or PRs. Thank you for the report!
