### ISSUE TITLE
Relief from "warning: already initialized constant" in supermarket release?

### ISSUE THREAD

**Issue by flatrocks** [opscode-cookbooks/firewall#58]
```
/var/.../cookbooks/firewall/libraries/provider_firewall_rule_firewalld.rb:60: warning: already initialized constant Chef::Provider::FirewallRuleFirewalld::CHAIN
/var/.../cookbooks/firewall/libraries/provider_firewall_rule_firewalld.rb:60: warning: previous definition of CHAIN was here
```  
ad infinitum

This seems fixed in c9240b8006cb8d0cebd5d01a24875103bb5c18d9 but with the most recent supermarket version, all the warnings are still making my test output useless.

It looks like there are a lot of balls in the air right now and it may be inappropriate for a new release at this time, but any tips on avoiding this problem?  Would it be reasonable to "depend" a previous version?

**Comment by martinb3** [comment]
Hi there -- I went ahead and did a maintenance release. The only thing in it is #57. Hope that helps!

**Comment by flatrocks** [comment]
Excellent!   Yes thanks, that was quite helpful.
