### ISSUE TITLE
Make the default zone configurable for firewalld

### ISSUE THREAD

**Issue by pietervogelaar** [opscode-cookbooks/firewall#71]
In the LWRP for firewalld exists the following line:

```
shell_out!('firewall-cmd', '--set-default-zone=drop')
```

The default zone is hardcoded here. Please make it configurable.

**Comment by martinb3** [comment]
Hi there -- I'm not sure the best way to integrate this into the cross-platform resource that covers iptables, firewalld, and ufw. @rdoorn @johnbellone What do you think? You've contributed to the firewalld provider the most.

**Comment by rdoorn** [comment]
what i think would work better, is to create an additional provider for setting the defaults, for example
zone "accept" do
   target "drop"
end
of in firewalld's case
zone "default" do
  target drop
end

not sure what the ufw equivelant is, but it would make it more configurable for people who have other default destinations for chains/zones.

**Comment by martinb3** [comment]
#84 added a helper for this, in https://github.com/opscode-cookbooks/firewall/blob/master/libraries/helpers_firewalld.rb:
```
      def firewalld_default_zone?(z)
        cmd = shell_out('firewall-cmd', '--get-default-zone')
        cmd.stdout =~ /^#{z}$/
      end

      def firewalld_default_zone!(z)
        shell_out!('firewall-cmd', "--set-default-zone=#{z}")
      end
```

**Comment by martinb3** [comment]
Added this as an option on the firewall resource. Thanks all!
