### ISSUE TITLE
UFW Firewall rule clear/flush

### ISSUE THREAD

**Issue by phene** [opscode-cookbooks/firewall#76]
It appears that the UFW provider will not delete old firewall rules that are no longer defined in a recipe.

**Comment by facastagnini** [comment]
Take a look at #36 , is that what you mean?

**Comment by martinb3** [comment]
Hi there -- currently, the firewall_rule resource behaves similarly to the file resource and many other resources; if it is no longer present, the file isn't deleted. If you'd like the firewall to always be flushed when chef runs, you can use the firewall resource with a flush action. #77 is the eventual goal, which should accomplish what you're looking for. Hope this helps.
