### ISSUE TITLE
[support] How to set firewall_rule in multiple cookbooks

### ISSUE THREAD

**Issue by patcon** [opscode-cookbooks/firewall#83]
I'm using `elkstack::acl`, but when also try to add some rules in a base cookbook for all servers, it's not picked up. The poise setup really confuses me, to be honest. I don't understand what's going on at this giant abstractions layer, but I'm not used to resources getting swallowed and failing to be acted upon

This is what I have in `base::firewall`:
```rb
firewall 'iptables' do
  action :nothing
  provider Chef::Provider::FirewallIptables
end

firewall_rule "allow ssh entries inbound" do
  provider    Chef::Provider::FirewallRuleIptables
  protocol    :tcp
  port        22  
  action      :allow
end
```

I have `base::firewall` in the runlist before `elkstack::acl`. When I go to check out the rules at the of the run with `iptables -L`, only the elkstack rules are there. If I put my own recipe after the elkstack one in the runlist, then ~~only its ssh rule shows up~~ EDIT: it *does* get appended.

Any suggestions? fwiw, my experience with this cookbook has not been wonderful, and I've spent lots of cycles trying to sort it out :(

EDIT: Ok, so it seems that if my recipe is placed before the `elkstack::acl` one, then it's ignored. If place afterward, it's added. This is pretty unexpected behaviour

**Comment by martinb3** [comment]
@patcon I apologize -- this cookbook is a bit in flux at the moment. It currently runs the firewall provider, and then all `firewall_rule`s in the order they appear.

Can you try declaring the `firewall` resource with an action other than `action :nothing`? Presumably you want to turn on the firewall in `base::firewall`, so you'd want an `:enable` action.

**Comment by martinb3** [comment]
We're working on refactoring the resources and providers so that they can generate an entire firewall config all at once, and then apply it, instead of running each rule individually.

**Comment by patcon** [comment]
Thanks Martin :) I did try it with the `:enable` action while troubleshooting, but saw the same thing.

fwiw, I'm still interested and I'll keep watching this space, but decided to cut my losses and go with the iptables cookbook for now

**Comment by martinb3** [comment]
Hi @patcon -- if you're up for it, #84 fixes many of the issues you encountered. If you'd like to give it a spin, and let me know your feedback, I'd be much obliged. Thanks!

**Comment by patcon** [comment]
Thanks @martinb3! I'll close this out for now
